# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 03:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0003_auto_20170130_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('REFI', 'refinance'), ('SALE', 'sale')], default='SALE', max_length=4),
        ),
    ]
