# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0009_auto_20170202_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.CharField(choices=[('Not Complete', 'Not Complete'), ('Complete', 'Complete'), ('Delivered', 'Delivered')], default='Not Complete', max_length=25),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='AVX3AVR', editable=False, max_length=10),
        ),
    ]
