# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 12:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0012_auto_20170203_0652'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='slug',
            field=models.SlugField(default='temp', max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='X3BN77M', editable=False, max_length=10),
        ),
    ]
