# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 17:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0013_auto_20170203_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This does not appear to be a valid address.', regex='^(\\d+) (\\w+)$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='completed_by',
            field=models.CharField(choices=[('ANON', 'No Employee Linked'), ('JBLE', 'Jamie Bledsoe'), ('BWI', 'Brandy Wills'), ('BBA', 'Brittany Backman'), ('MFO', 'Micaela Fouda'), ('EGL', 'Elisha Glover'), ('NWA', 'Natasha Wawr?')], default='ANON', max_length=4),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='O7ZG1BF', editable=False, max_length=10),
        ),
    ]
