# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 18:13
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0030_auto_20170205_1212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='This does not appear to be a valid address.', regex='^(\\d+) (\\w?.?\\s?\\d+?.?\\w+ ?\\w+)$')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='WRAKSSF', editable=False, max_length=10),
        ),
    ]
