# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 19:29
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0038_auto_20170205_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=100, validators=[django.core.validators.RegexValidator(message='This does not appear to be a valid address. \n\t\t\t\tTo submit your order we must be provided with a complete street address. \n\t\t\t\tIf an address is not available, then please provide only the street name \n\t\t\t\tand the legal description in the CAD Number field, and leave the address blank.', regex="^(\\d+\\s(\\w+.? ?\\d+\\w+)?\\w+'?\\s?\\w+.?)$")]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='H1DBQXU', editable=False, max_length=10),
        ),
    ]
