# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0040_auto_20170205_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='rush_status',
            field=models.CharField(choices=[('REG', '8 business days'), ('2BD', '2 business day rush')], default='REG', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='IZLII07', editable=False, max_length=10),
        ),
    ]
