# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-13 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soa', '0041_auto_20170205_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='completed',
            field=models.CharField(choices=[('Not Complete', 'Not Complete'), ('Complete - Delivery Pending', 'Complete - Delivery Pending'), ('Delivered', 'Delivered')], default='Not Complete', max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='E4NIXLY', editable=False, max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('Sale', 'Sale'), ('Refi', 'Refinance')], default='SALE', max_length=8),
        ),
    ]
